### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [scmetcalf/prj-rev-bwfs-dasmoto#6]
**Grade:** Needs Improvement

**Summary:** This project has a lot of good work and is really close to meeting the spec! Your CSS is clean and HTML achieves the objective, but we just want to clean it up to make sure we're following best practices! A few areas of improvement are remembering consistent HTML indentation (indent children from parent elements), making sure all HTML is wrapped with a tag (usage of p, headings, etc.), and trying to reduce repeated CSS styles! 

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline- block.html.

I’d also suggest checking out HTML codes, which will help explain my comment on the & usage in your HTML!

**Comment by scmetcalf** [comment]
Appreciate the feedback.  This is why I take the class and your positive comments along with critical analysis helps. Thank you for your time!
